In [1]:
using LinearAlgebra, Statistics

In [2]:
a = [10, 20, 30]

3-element Vector{Int64}:
 10
 20
 30

In [3]:
a = [1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [4]:
typeof(randn(100))

Vector{Float64} (alias for Array{Float64, 1})

In [5]:
ndims(a)

1

In [6]:
size(a)

(3,)

In [7]:
Array{Int64, 1} == Vector{Int64}
Array{Int64, 2} == Matrix{Int64}

true

In [8]:
[1, 2, 3] == [1; 2; 3]  # both column vectors

true

In [9]:
[1 2 3]  # a row vector is 2-dimensional

1×3 Matrix{Int64}:
 1  2  3

In [10]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [11]:
zeros(2, 2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [12]:
fill(5.0, 2, 2)

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [13]:
x = Array{Float64}(undef, 2, 2)

2×2 Matrix{Float64}:
 6.20799e-310  6.208e-310
 6.208e-310    6.208e-310

In [14]:
fill(0, 2, 2)  # fills with 0, not 0.0

2×2 Matrix{Int64}:
 0  0
 0  0

In [15]:
fill(false, 2, 2)  # produces a boolean matrix

2×2 Matrix{Bool}:
 0  0
 0  0

In [16]:
x = [1, 2, 3]
y = x
y[1] = 2
x

3-element Vector{Int64}:
 2
 2
 3

In [17]:
x = [1, 2, 3]
y = copy(x)
y[1] = 2
x

3-element Vector{Int64}:
 1
 2
 3

In [18]:
x = [1, 2, 3]
y = similar(x)
y

3-element Vector{Int64}:
 0
 1
 1

In [19]:
x = [1, 2, 3]
y = similar(x, 4)  # make a vector of length 4

4-element Vector{Int64}:
                   4
 5908731679541953035
 2522024590197130240
      12532946567172

In [20]:
x = [1, 2, 3]
y = similar(x, 2, 2)  # make a 2x2 matrix

2×2 Matrix{Int64}:
                 8    1099511628033
 72340168526266625  125651426213896

In [21]:
a = [10, 20, 30, 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [22]:
a = [10 20 30 40]  # two dimensional, shape is 1 x n

1×4 Matrix{Int64}:
 10  20  30  40

In [23]:
ndims(a)

2

In [24]:
a = [10 20; 30 40]  # 2 x 2

2×2 Matrix{Int64}:
 10  20
 30  40

In [25]:
a = [10; 20; 30; 40]

4-element Vector{Int64}:
 10
 20
 30
 40

In [26]:
a = [10 20 30 40]'

4×1 adjoint(::Matrix{Int64}) with eltype Int64:
 10
 20
 30
 40

In [27]:
ndims(a)

2

In [28]:
a = [10 20 30 40]
a[end - 1]

30

In [29]:
a = [1 2; 3 4]
b = a[:, 2]
@show b
a[:, 2] = [4, 5] # modify a
@show a
@show b;

b = [2, 4]
a = [1 4; 3 5]
b = [2, 4]


In [30]:
a = [1 2; 3 4]
@views b = a[:, 2]
@show b
a[:, 2] = [4, 5]
@show a
@show b;

b = [2, 4]
a = [1 4; 3 5]
b = [4, 5]


In [31]:
@views b = a[:, 2]
view(a, :, 2) == b

true

In [32]:
a = [1 2; 3 4]
b_slice = a[:, 2]
@show typeof(b_slice)
@show typeof(a)
@views b = a[:, 2]
@show typeof(b);

typeof(b_slice) = Vector{Int64}
typeof(a) = Matrix{Int64}
typeof(b) = SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}


In [33]:
d = [1.0, 2.0]
a = Diagonal(d)

2×2 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅ 
  ⋅   2.0

In [34]:
@show 2a
b = rand(2, 2)
@show b * a;

2a = [2.0 0.0; 0.0 4.0]
b * a = [0.14285569613748172 0.5834002555665305; 0.9424137880852714 0.044346653576904815]


In [35]:
b = [1.0 2.0; 3.0 4.0]
b - Diagonal([1.0, 1.0])  # poor style, inefficient code

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

In [36]:
a = [-1, 0, 1]

@show length(a)
@show sum(a)
@show mean(a)
@show std(a)      # standard deviation
@show var(a)      # variance
@show maximum(a)
@show minimum(a)
@show extrema(a)  # (mimimum(a), maximum(a))

length(a) = 3
sum(a) = 0
mean(a) = 0.0
std(a) = 1.0
var(a) = 1.0
maximum(a) = 1
minimum(a) = -1
extrema(a) = (-1, 1)


(-1, 1)

In [37]:
a = ones(1, 2)

1×2 Matrix{Float64}:
 1.0  1.0

In [38]:
b = ones(2, 2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [39]:
a * b

1×2 Matrix{Float64}:
 2.0  2.0

In [40]:
b * a'

2×1 Matrix{Float64}:
 2.0
 2.0

In [41]:
A = [1 2; 2 3]

2×2 Matrix{Int64}:
 1  2
 2  3

In [42]:
ones(2, 2) * ones(2, 2)   # matrix multiplication

2×2 Matrix{Float64}:
 2.0  2.0
 2.0  2.0

In [43]:
ones(2, 2) .* ones(2, 2)   # element by element multiplication

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [44]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [45]:
det(A)

-2.0

In [46]:
tr(A)

5

In [47]:
eigvals(A)

2-element Vector{Float64}:
 -0.3722813232690143
  5.372281323269014